# Generated by Django 3.0.6 on 2020-05-16 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='analayzed_data',
            new_name='analyzed_data',
        ),
    ]
